improve society
MyCompta/MyCompta_front pull request #52
Opened 2024-03-27 21:52 UTC by MathieuAmacher

utilisation d'atom pour ciruclation fluide en new et showsociety

2024-03-27 22:33 UTC, totycos approved these changes

2024-03-27 23:08 UTC, LoulergueC requested changes
´´´
src/pages/society/IndexSocieties.tsx(70,69): error TS2322: Type 'number' is not assignable to type 'string'.
´´´
Id: String(...);

2024-03-28 16:58 UTC, LoulergueC approved these changes

2024-03-28 17:12 UTC, LoulergueC requested changes
Merge conflicts unresolved on `src/atom/societyAtom.tsx`

2024-03-28 19:42 UTC, LoulergueC approved these changes

2024-03-28 19:44 UTC, merged